### PR TITLE
Added switches on the menu UI

### PR DESCRIPTION
**Pull request by ppekko**
cured a case of If{} else

### CODE REVIEW

**Comment by cuevavirus** [comment]
i dont understand this

you replace unix line ends with windows line ends for half the file
you indented randomly and with spaces instead of tabs
you left trailing whitespace
you doubled the line count replacing ifs with switch cases

lacking subtlety not even good attempt at trolling

**Comment by KuromeSan** [comment]
Perhaps hes using a linux based text editor. Whereas I used notepad++ on windows? IDK.

**Comment by LiEnby** [comment]
Perhaps he used a UNIX based editor to edit the src? Which was created using windows based editor

**Comment by cuevavirus** [comment]
99439954_1277549829114829_6441297225589981184_o

**Comment by ppekko** [comment]
lmfao calm down

**Pull request closed without merging**
